Fix Open ID Connect bug
ehan/liferay-portal pull request #3
Opened 2018-08-01 22:04 UTC by jrao

Fix Open ID Connect bug

2018-08-02 19:03 UTC, ehan requested changes

2018-08-02 19:03 UTC, ehan commented on modules/apps/foundation/portal-security-sso/portal-security-sso-openid-connect-impl/src/main/java/com/liferay/portal/security/sso/openid/connect/internal/OpenIdConnectServiceHandlerImpl.java
> +			openIdConnectSession = getOpenIdConnectSession(httpSession);
Better have this return a null and do a null check. Create a get that can return a null

2018-08-02 19:03 UTC, ehan commented on modules/apps/foundation/portal-security-sso/portal-security-sso-openid-connect-impl/src/main/java/com/liferay/portal/security/sso/openid/connect/internal/OpenIdConnectServiceHandlerImpl.java
> +		if (openIdConnectProviderName.equals(openIdProviderName)) {
Return StringUtil.equals(), no need to do the return true/false

2018-08-02 19:03 UTC, ehan commented on modules/apps/foundation/portal-security-sso/portal-security-sso-openid-connect-impl/src/main/java/com/liferay/portal/security/sso/openid/connect/internal/OpenIdConnectServiceHandlerImpl.java
>  		httpSession.setAttribute(
Move this to only execute when creating a new OIDCSession

2018-09-06 13:11 UTC, jrao commented
Superceded by https://github.com/ehan/liferay-portal/pull/5

2018-09-06 13:11 UTC, closed without merging